// <auto-generated />
using Application.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Services.DatabaseMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "days", new[] { "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "weekday", "weekend" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer_data_us");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "plpgsql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_raster");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_sfcgal");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Domain.Entities.BusinessHoursEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<LocalTime?>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("close_time");

                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week_id");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<LocalTime?>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("open_time");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_business_hours");

                    b.HasIndex("DayOfWeekId")
                        .HasDatabaseName("ix_business_hours_day_of_week_id");

                    b.HasIndex("VenueId", "DayOfWeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_venue_id_day_of_week_id");

                    b.ToTable("business_hours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CloseTime = new NodaTime.LocalTime(15, 0),
                            DayOfWeekId = 1,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(10, 0),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 2,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 3,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 4,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 5,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 6,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 7,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 30),
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CloseTime = new NodaTime.LocalTime(23, 0),
                            DayOfWeekId = 1,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 9L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 2,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 3,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 4,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            CloseTime = new NodaTime.LocalTime(0, 0),
                            DayOfWeekId = 5,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            CloseTime = new NodaTime.LocalTime(2, 0),
                            DayOfWeekId = 6,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            CloseTime = new NodaTime.LocalTime(2, 0),
                            DayOfWeekId = 7,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            CloseTime = new NodaTime.LocalTime(14, 0),
                            DayOfWeekId = 1,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(10, 0),
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            DayOfWeekId = 2,
                            IsClosed = true,
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 17L,
                            CloseTime = new NodaTime.LocalTime(21, 0),
                            DayOfWeekId = 3,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 18L,
                            CloseTime = new NodaTime.LocalTime(21, 0),
                            DayOfWeekId = 4,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 19L,
                            CloseTime = new NodaTime.LocalTime(21, 0),
                            DayOfWeekId = 5,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 20L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 6,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 21L,
                            CloseTime = new NodaTime.LocalTime(22, 0),
                            DayOfWeekId = 7,
                            IsClosed = false,
                            OpenTime = new NodaTime.LocalTime(11, 0),
                            VenueId = 3L
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.DayOfWeekEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsWeekday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_weekday");

                    b.Property<int>("IsoNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iso_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("short_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_days_of_week");

                    b.HasIndex("IsoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_days_of_week_iso_number");

                    b.ToTable("days_of_week", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsWeekday = false,
                            IsoNumber = 7,
                            Name = "Sunday",
                            ShortName = "SUN",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            IsWeekday = true,
                            IsoNumber = 1,
                            Name = "Monday",
                            ShortName = "MON",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            IsWeekday = true,
                            IsoNumber = 2,
                            Name = "Tuesday",
                            ShortName = "TUE",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            IsWeekday = true,
                            IsoNumber = 3,
                            Name = "Wednesday",
                            ShortName = "WED",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            IsWeekday = true,
                            IsoNumber = 4,
                            Name = "Thursday",
                            ShortName = "THU",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            IsWeekday = true,
                            IsoNumber = 5,
                            Name = "Friday",
                            ShortName = "FRI",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            IsWeekday = false,
                            IsoNumber = 6,
                            Name = "Saturday",
                            ShortName = "SAT",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_special_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_special_categories_name");

                    b.ToTable("special_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Food specials, appetizers, and meal deals",
                            Icon = "🍔",
                            Name = "Food",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Drink specials, happy hours, and beverage promotions",
                            Icon = "🍺",
                            Name = "Drink",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Live music, DJs, trivia, karaoke, and other events",
                            Icon = "🎵",
                            Name = "Entertainment",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CronSchedule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cron_schedule");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<LocalTime?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<int>("SpecialCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("special_category_id");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_specials");

                    b.HasIndex("SpecialCategoryId")
                        .HasDatabaseName("ix_specials_special_category_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_specials_venue_id");

                    b.ToTable("specials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CronSchedule = "0 21 * * 5,6",
                            Description = "Live music showcasing the best in local, regional, and national talent. Various genres from rock to jazz.",
                            EndTime = new NodaTime.LocalTime(23, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 3,
                            StartDate = new NodaTime.LocalDate(2025, 5, 3),
                            StartTime = new NodaTime.LocalTime(21, 0),
                            Title = "Live Music Friday/Saturday",
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CronSchedule = "0 16 * * 1-5",
                            Description = "Enjoy $1 off all draft beers and $5 house wines.",
                            EndTime = new NodaTime.LocalTime(18, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 2,
                            StartDate = new NodaTime.LocalDate(2025, 5, 1),
                            StartTime = new NodaTime.LocalTime(16, 0),
                            Title = "Happy Hour",
                            VenueId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Sweet and spicy chicken sandwich with sweet n spicy sauce, lettuce, and pickles.",
                            EndDate = new NodaTime.LocalDate(2025, 5, 27),
                            EndTime = new NodaTime.LocalTime(22, 0),
                            IsActive = true,
                            IsRecurring = false,
                            SpecialCategoryId = 1,
                            StartDate = new NodaTime.LocalDate(2025, 5, 20),
                            StartTime = new NodaTime.LocalTime(11, 0),
                            Title = "Weekly Burger Special - Sweet & Spicy Chicken Sandwich",
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CronSchedule = "0 21 * * 3",
                            Description = "Pub Trivia with first and second place prizes. Sponsored by Bacardi Oakheart.",
                            EndTime = new NodaTime.LocalTime(23, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 3,
                            StartDate = new NodaTime.LocalDate(2025, 5, 22),
                            StartTime = new NodaTime.LocalTime(21, 0),
                            Title = "Wednesday Night Quizzo",
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            CronSchedule = "0 11 * * 2",
                            Description = "Every Tuesday is Mug Club Night. Our valued Mug club members enjoy their First beer, of their choice, on US!!",
                            EndTime = new NodaTime.LocalTime(23, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 2,
                            StartDate = new NodaTime.LocalDate(2025, 5, 21),
                            StartTime = new NodaTime.LocalTime(11, 0),
                            Title = "Mug Club Tuesday",
                            VenueId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            CronSchedule = "0 10 * * 0",
                            Description = "Special brunch menu served from 10am to 2pm every Sunday.",
                            EndTime = new NodaTime.LocalTime(14, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 1,
                            StartDate = new NodaTime.LocalDate(2025, 5, 18),
                            StartTime = new NodaTime.LocalTime(10, 0),
                            Title = "Sunday Brunch",
                            VenueId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            CronSchedule = "0 16 * * 2-6",
                            Description = "Enjoy our specially crafted cocktails at a reduced price.",
                            EndTime = new NodaTime.LocalTime(18, 0),
                            IsActive = true,
                            IsRecurring = true,
                            SpecialCategoryId = 2,
                            StartDate = new NodaTime.LocalDate(2025, 5, 21),
                            StartTime = new NodaTime.LocalTime(16, 0),
                            Title = "Cocktail Hour",
                            VenueId = 3L
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_venue_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_categories_name");

                    b.ToTable("venue_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dining establishments offering food and beverages",
                            Icon = "🍽️",
                            Name = "Restaurant",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Venues focused on drinks and nightlife",
                            Icon = "🍸",
                            Name = "Bar",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Casual spots for coffee and light meals",
                            Icon = "☕",
                            Name = "Cafe",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Venues for dancing and late-night entertainment",
                            Icon = "🪩",
                            Name = "Nightclub",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Casual venues with food, drinks, and often live music",
                            Icon = "🍺",
                            Name = "Pub",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Venues producing wine, offering tastings, food pairings, and live music",
                            Icon = "🍷",
                            Name = "Winery",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Description = "Venues brewing their own beer, often with food and live music",
                            Icon = "🍻",
                            Name = "Brewery",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sophisticated venues with cocktails, small plates, and live music",
                            Icon = "🛋️",
                            Name = "Lounge",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 10,
                            Description = "Intimate dining venues with quality food, wine, and occasional live music",
                            Icon = "🥂",
                            Name = "Bistro",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("SecondaryAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secondary_address");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street_address");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_venues_category_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_venues_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_venues_name");

                    b.ToTable("venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 7,
                            Country = "United States",
                            Description = "Local craft brewery featuring house-made beers, pub fare, and live entertainment in a cozy atmosphere.",
                            Email = "info@bullfrogbrewery.com",
                            IsActive = true,
                            Locality = "Williamsport",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-77.0057192 41.240432)"),
                            Name = "Bullfrog Brewery",
                            PhoneNumber = "(570) 326-4700",
                            PostalCode = "17701",
                            Region = "PA",
                            StreetAddress = "229 W 4th St",
                            Website = "https://bullfrogbrewery.com"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1,
                            Country = "United States",
                            Description = "Family-friendly restaurant and ale house serving American cuisine with a great selection of craft beers and cocktails.",
                            Email = "info@thebrickyard.net",
                            IsActive = true,
                            Locality = "Williamsport",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-77.0037646 41.2409825)"),
                            Name = "The Brickyard Restaurant & Ale House",
                            PhoneNumber = "(570) 322-3876",
                            PostalCode = "17701",
                            Region = "PA",
                            StreetAddress = "343 Pine St",
                            Website = "https://thebrickyard.net"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2,
                            Country = "United States",
                            Description = "Upscale gastropub featuring craft cocktails, local beers, and elevated bar food in a sophisticated atmosphere.",
                            Email = "info@thecrookedgoose.com",
                            IsActive = true,
                            Locality = "Williamsport",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-77.0047521 41.2407201)"),
                            Name = "The Crooked Goose",
                            PhoneNumber = "(570) 360-7435",
                            PostalCode = "17701",
                            Region = "PA",
                            StreetAddress = "215 W 4th St",
                            Website = "https://thecrookedgoose.com"
                        });
                });

            modelBuilder.Entity("Application.Domain.Entities.BusinessHoursEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.DayOfWeekEntity", "DayOfWeek")
                        .WithMany("BusinessHours")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_days_of_week_day_of_week_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany("BusinessHours")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_venues_venue_id");

                    b.Navigation("DayOfWeek");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.SpecialCategoryEntity", "Category")
                        .WithMany("Specials")
                        .HasForeignKey("SpecialCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_specials_special_categories_special_category_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany("Specials")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specials_venues_venue_id");

                    b.Navigation("Category");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.VenueCategoryEntity", "Category")
                        .WithMany("Venues")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venues_venue_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Application.Domain.Entities.DayOfWeekEntity", b =>
                {
                    b.Navigation("BusinessHours");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialCategoryEntity", b =>
                {
                    b.Navigation("Specials");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueCategoryEntity", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("Specials");
                });
#pragma warning restore 612, 618
        }
    }
}
